dcos/dcos-test-utils

dcos_test_utils/dcos_api_session.py
dcos_test_utils/marathon.py
dcos_test_utils/package.py

- Also make poll_marathon_for_app_deployment a public method in Marathon so you can use it to check if your installation completed
Reference: [Cosmos REST API docs.](https://downloads.dcos.io/cosmos/0.4.0-SNAPSHOT-232-master-2fdc5cf8ad/package.html#)
WIP, am working on tests. See https://github.com/dcos/dcos/pull/1748
For https://jira.mesosphere.com/browse/DCOS_OSS-1394

Package api support

---

dcos_test_utils/dcos_api_session.py
dcos_test_utils/marathon.py

* fixes unconnected timeout method for deploy
* untangles deployment methods
* moves test case specific code to live with
test cases

Refactor marathon utilities

---

dcos_test_utils/dcos_cli.py
dcos_test_utils/dcoscli.py

Simple utility for running the dcos-cli

Add CLI harness from downstream

---

dcos_test_utils/onprem.py

Part of https://jira.mesosphere.com/browse/QUALITY-1608

bootstrap host processed separately from cluster hosts

---

dcos_test_utils/dcos_api.py

Fixes https://jira.mesosphere.com/browse/DCOS-19612

[WIP] DCOS-19612: Fix unhashable type error

---

dcos_test_utils/dcos_cli.py

[Mailing thread](https://groups.google.com/a/mesosphere.io/forum/#!topic/dcos-cli/ogpfYwFmrPE) for a detailed discussion on why this is done the way it is done.
Bump PR : https://github.com/dcos/dcos/pull/2049

Add latest version of cli

---

dcos_test_utils/dcos_api.py

See https://jira.mesosphere.com/browse/DCOS-19866
(edit: since making this PR, I made a separate JIRA for it)

[DCOS-19866] Always log what the metronome status code is

---

dcos_test_utils/helpers.py
dcos_test_utils/onprem.py
dcos_test_utils/ssh_client.py
dcos_test_utils/test_ssh_client.py

This is the core of the dcos_installer project in dcos/dcos. It is being cannabilized here so that other tools may do coordinated asynchronous command across many hosts in a reliable manner. 
Additionally, this will allow the downstream project of dcos/dcos-launch to be independent of the ssh-driven installer by simply doing it on its own.

Add MultiRunner and refactor ssh_client

---

dcos_test_utils/dcos_api.py

https://jira.mesosphere.com/browse/DCOS-20200

Only raise exception if a list is None

---

dcos_test_utils/dcos_api.py
dcos_test_utils/helpers.py

We need more verbose logs to be able to debug the error.

Log the received response code and content DCOS-20444

---

dcos_test_utils/dcos_api.py

dcos-signal tests[1] failing; there is a race condition where
`health-unit-dcos-checks-poststart-service-unhealthy` is expected to
return `0`, but the service unit sometimes has not yet completed and
returns `1` instead.  This check waits for all services to return
healthy states (`0`) before declaring a DC/OS cluster "up".
- new `_wait_for_all_healthy_services()` function, added to `wait_for_dcos`
[1] https://github.com/dcos/dcos/blob/master/packages/dcos-integration-test/extra/test_composition.py#L219

(QUALITY-1869) wait for `dcos-checks-poststart'

---

dcos_test_utils/dcos_api.py
dcos_test_utils/diagnostics.py
dcos_test_utils/helpers.py

https://jira.mesosphere.com/browse/QUALITY-1819
Corresponding dcos PR https://github.com/dcos/dcos/pull/2485

add methods for getting diagnostics report to health endpoint

---

README.md
dcos_test_utils/dcos_api.py
integration_test.py
tox.ini

This test expects a cluster to be provided externally and tests authentication and basic DC/OS service health

Add most basic integration test

---

conftest.py
dcos_test_utils/dcos_api.py
dcos_test_utils/enterprise.py
integration_test.py
pytest_dcos/plugin.py
setup.py
tests/test_plugin.py

formalizes the `dcos_api_session` 
PR for using this in dcos/dcos: https://github.com/dcos/dcos/pull/2637
https://jira.mesosphere.com/browse/QUALITY-1883

Add pytest plugin

---

dcos_test_utils/dcos_cli.py

To make the integration tests more robust, Pytest fixtures were modified as part of https://jira.mesosphere.com/browse/DCOS-38213. A few of these changes are more appropriately added to `dcos-test-utils`:
- Allow temporary directory to be provided, so it can be deleted later.
- Increase buffer size, to reduce loops iterations.
- Allow CLI state cleanup to work if directory does not exist.
- [DCOS-38213](https://jira.mesosphere.com/browse/DCOS-38213) dcoscli fixture times-out while downloading CLI
Is this change going to be propagated up into another repo? Test the change by bumping the `dcos-test-utils` SHA to point to these changes to test it. Link the corresponding …

CLI modifications to make tests more robust

---

PULL_REQUEST_TEMPLATE.md

The PULL_REQUEST_TEMPLATE.md was copy-pasted from dcos-launch and still had the wrong link to the TeamCity jobs. This fixes that.
[Integration tests](https://teamcity.mesosphere.io/project.html?projectId=DcosIo_DcosLaunch_IntegrationTests&tab=projectOverview) were run and
**PLEASE FILL IN …

fix links to teamcity jobs in PR template

---

dcos_test_utils/dcos_cli.py

Checking the output is not safe and we should only check for stderr to know if the login step went well or not: https://teamcity.mesosphere.io/viewLog.html?buildId=1280161&buildTypeId=DcOs_Enterprise_Test_Inte_AwsOnpremWStaticBackendAndSecurityStrict
[Integration …

Removed stdout check in 'login_enterprise()'.

---

dcos_test_utils/dcos_cli.py

This will facilitate debugging.
- [DCOS-46195](https://jira.mesosphere.com/browse/DCOS-46195) CLI says 'URL [https://downloads.mesosphere.io/cli/ ... /dcos-enterprise-cli] is unreachable
**What is …

Made installation of the dcos-ee-cli very verbose.

---

dcos_test_utils/diagnostics.py

This increases the wait time for a diagnostics bundle from 2 minutes to 20 minutes.
Corresponding PR that this will partially replace: https://github.com/dcos/dcos/pull/3952
- [DCOS-41819](https://github.com/dcos/dcos/pull/3952) 
**What is the review process and when will my changes land?**
All PRs require 2 approvals using GitHub's …

Port over part of DCOS-41819 PR

---

dcos_test_utils/marathon.py

https://jira.mesosphere.com/browse/DCOS-51632

Revert "By default set ignore_failed_tasks to True"

---

dcos_test_utils/dcos_api.py

* https://jira.mesosphere.com/browse/DCOS-45732 
* Retry on HTTP 502 observed briefly during agent restarts.

Retry on HTTP 502 observed briefly during agent restarts.

---

dcos_test_utils/dcos_api.py

* https://jira.mesosphere.com/browse/DCOS-45732

Increased the Stop Max limit to 60.

---

dcos_test_utils/dcos_cli.py

Removed unnecessary dcos-enterprise-cli installation.
- [DCOS-54793](https://jira.mesosphere.com/browse/DCOS-54793) Retry Enterprise CLI download in integration test suite.
**What is the review …

Removed unnecessary dcos-enterprise-cli installation.

---

dcos_test_utils/diagnostics.py
requirements.txt
setup.py
tests/test_dcos_diagnostics.py

Fixes: https://jira.mesosphere.com/browse/DCOS_OSS-5435
Add support for new diagnostics endpoints
- [DCOS_OSS-5435](https://jira.mesosphere.com/browse/DCOS_OSS-5435) Implement new API in dcos-test-utils
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT REMOVE ANY SECTIONS ABOVE THIS …

Add new DCOS Diagnostics API support

---

dcos_test_utils/etcd.py
dcos_test_utils/tls.py
setup.py

Adds tooling for etcd and tls related integration tests.
- https://jira.d2iq.com/browse/D2IQ-59030 `introduce RBAC authn&authz`
- https://jira.d2iq.com/browse/D2IQ-64356 `E2E test for custom external certificate feature`
* https://github.com/dcos/dcos/pull/6817
* https://github.com/mesosphere/dcos-enterprise/pull/7291
**What is the …

Add etcd and tls tooling
