dcos/dcos-test-utils

- dcos_test_utils/marathon.py
Timeout was 2 minutes while mesos-level timeout for
task execution is 10 minutes. Making these times comparable
for deployment allows mesos to actually retry
> Increase app deployment timeout

- dcos_test_utils/marathon.py
I think there was a short period of time when it was hard coded, but not anymore.
```python
raise Exception("Application deployment failed - operation was not "
-                            "completed in 2 minutes.")
+                            "completed in {} seconds.".format(timeout))
```
> non-hard-coded error message in marathon.deploy_app

- dcos_test_utils/package.py
- version is optional (should get latest if not provided)
- add optional `options` and `appId`
Required for tweeter enterprise integration test (marathon-lb needs installation options) 
https://github.com/dcos/dcos/pull/1833/files
Merging this will require updating the integration tests that use cosmos to pass the package version as a kwarg.
> make the package/install endpoint match the API parameters

- dcos_test_utils/dcos_cli.py
- dcos_test_utils/onprem.py
This is to fix the following error when executing a `dcos security` command using dcos_cli:
`Failed to execute script dcos-security\nTraceback (most recent call last):\n  File "dcos-security.py", line 19, in <... your issue by exporting the\nfollowing environment variables:\n\n    export LC_ALL=C.UTF-8\n    export LANG=C.UTF-8\n`
> Adding LC_ALL & LANG to dcos_cli environment.

- dcos_test_utils/dcos_api.py
In the current implementation
```
r = self.get('/marathon/ui/')
```
Results in 404, and we find it OK because the service is not 500'ing
However, I think, it is better to verify for 
`v2/info` endpoint as [documented by the API ](http://mesosphere.github.io/marathon/api-console/index.html)to be up.
[v2/info endpoint ](https://github.com/mesosphere/marathon/blob/v1.3.0/docs/docs/rest-api/public/api/v2/info.raml )was added in `1.3.0` and it should support our existing pre and post upgrade scenarios of DCOS 1.8+
> DCOS 19496 - Wait for Marathon up - check for v2/info endpoint

- dcos_test_utils/dcos_api.py
Users must knownling NOT supply a host list instead
of blindly allowing the harness to set the hosts
> Require users to opt-in to auto-detect clusters

- dcos_test_utils/enterprise.py
- dcos_test_utils/iam.py
- dcos_test_utils/marathon.py
Use `raise_for_status` to get slightly better error messages than
```
s = '404 Not Found: service not found.\n'
...
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
```
https://jira.mesosphere.com/browse/QUALITY-1614
> raise_for_status on responses before trying to extract json

- dcos_test_utils/marathon.py
- tox.ini
If an exception is raised in a code block with these context managers, the apps will live on forever
> Ensure apps or pods are deleted after failure

- dcos_test_utils/ssh_client.py
- dcos_test_utils/test_ssh_client.py
Previously this used `cat` though SSH to avoid having to reformat the SSH command to use a tunnel in the case of SCP where `-P` is used instead of `-p`
> Refactor SshClient to use SCP for copying

- dcos_test_utils/logger.py
if `noisy_modules` is given, additional modules can have their log-level reduced
> Allow dampening optional modules

- dcos_test_utils/dcos_api.py
- dcos_test_utils/enterprise.py
Refactors create and wait_for_dcos to provide API sessions in the same state. More specifically, the CA cert and the initial RID cache are both implicitly set in the enterprise session so that there is no difference when using the open session
> Consistent Cluster Session Setup

- dcos_test_utils/dcos_api.py
- dcos_test_utils/diagnostics.py
- dcos_test_utils/enterprise.py
- dcos_test_utils/helpers.py
- dcos_test_utils/marathon.py
- dcos_test_utils/package.py
- integration_test.py
- tests/test_dcos_api.py
For background, see: https://jira.mesosphere.com/browse/DCOS-13496
This PR makes it such that the URL passing is raw -- without hidden logic.
Unit test was added to clearly demonstrate URL handling.
Marathon integration test was added to ensure refactor does not break modules
> Simplify URL path handing in ApiClientSession

- dcos_test_utils/ssh_client.py
- tests/test_ssh_client.py
It still defaults to assuming local->remote, so previous uses of it shouldn't be affected
> ssh client copy_file bidirectional instead of always assuming local to remote copy

- dcos_test_utils/dcos_api.py
- dcos_test_utils/enterprise.py
I'd like to use the `_authenticate_default_user_public` in the resilience tests.
@adamtheturtle strongly suggested to not call private Python methods, therefore I now would like to make it a public method. If there are any objections against this please comment here.
> Make _authenticate_default_user public

- PULL_REQUEST_TEMPLATE.md
JIRA was cleaned up so that the QUALITY project doesn't exist, and tickets that were formerly put there now go into DCOS.
None
None
None
[Integration tests](https://teamcity.mesosphere.io/project.html?projectId=DcosIo_DcosLaunch_IntegrationTests&tab=projectOverview) were run and
> update QUALITY jira project to DCOS

- dcos_test_utils/dcos_cli.py
- tests/test_dcos_cli.py
Add logging of stderr when a command fails in the `dcos_cli` module.
- [DCOS_OSS-3620](https://jira.mesosphere.com/browse/DCOS_OSS-3620) Log stderr on failing command execution
https://github.com/dcos/dcos/pull/2971
Changes logging only, tested in local repo
Changes logging only, tested in local repo
[Integration tests](https://teamcity.mesosphere.io/project.html?projectId=DcosIo_DcosLaunch_IntegrationTests&tab=projectOverview) were run and
**PLEASE FILL IN THE TEMPLATE ABOVE** / **DO NOT …
> Display stderr when CLI command fails

- dcos_test_utils/dcos_api.py
This is needed for Hybrid cloud testing with Windows nodes spawned via dcos-launch
Currently the Environment variables for WINDOWS_HOSTS and WINDOWS_PUBLIC_HOSTS are ignored .
This will add the Windows nodes to the slaves , public_slaves list
> Add support for Windows Agents

- dcos_test_utils/ssh_client.py
This commit solves a bug that `wait_for_ssh_connection` can be blocked indefinitely if it's not possible to establish an SSH connection to the server.
The proposed is a "fallback" solution, meaning that it just enforces a maximum number of retries (30 minutes). Ideally, the `tunnel.command` should check for authentication errors and throw a different type of exception.
- [DCOS-41428](https://jira.mesosphere.com/browse/DCOS-41428) DC/OS launch waiting indefinitely for SSH to complete
> Fix indefinite blocking of wait_for_ssh_connection

- dcos_test_utils/dcos_api.py
Fix endpoints for mesos slaves state
Currently _wait_for_srouter_slaves_endpoints function is broken :
Method here: https://github.com/dcos/dcos-test-utils/blob/master/dcos_test_utils/dcos_api.py#L357-L382
Error log here:  https://pastebin.com/EspfqANM
The API call that is executed here: https://github.com/dcos/dcos-test-utils/blob/master/dcos_test_utils/dcos_api.py#L375-L376    is returning 404 errors from the Windows nodes 
According to the documentation : http://mesos.apache.org/documentation/latest/endpoints/slave/state/  :  the endpoint address should not have the .json ending
Removing '.json' from the uri returns 200 from both Linux and Windows nodes and the tests pass.
> Fix endpoint for slaves state

- dcos_test_utils/ssh_client.py
[DCOS-42480](https://jira.mesosphere.com/browse/DCOS-42480) will start to make use of mount volumes for package registry. The test harness requres use of ssh_client.py to setup mount volumes on the remote agents. 
While trying to run a ssh sub-process, invocations via `subprocess.check_call()` and `subprocess.check_output()` return a return code of 127 which implies `ssh` is not found on the `PATH` even when it was.
Python 3.5 adds the [subprocess.run()](https://docs.python.org/3/library/subprocess.html#using-the-subprocess-module) call which is the recommended approach for subprocess calls and allows for explicitly passing in a `PATH`. 
This PR fixes the bug being faced and updates to the recommended approach for subprocess calls. …
> Use subprocess.run instead of subprocess.check_call and check_output in ssh_client.py

- dcos_test_utils/dcos_cli.py
We now use the 1.12 CLI but some tests started to fail in DC/OS EE. These commits are here to fix the situation (it will also require a fix in DC/OS EE).
- [DCOS-44391](https://jira.mesosphere.com/browse/DCOS-44391) Change of --global flag behavior in CLI causes the dcos-enterprise tests to fail.
[Integration tests](https://teamcity.mesosphere.io/project.html?projectId=DcosIo_DcosTestUtils) …
> Fixed CLI usage to resolve DC/OS EE integration test issues.

- dcos_test_utils/dcos_api.py
This allows some integration tests to be run if there are no agents (or public agents) in the cluster.
See https://jira.mesosphere.com/browse/DCOS_OSS-3862.
- [DCOS_OSS-3862](https://jira.mesosphere.com/browse/DCOS_OSS-3862) DC/OS Test Utils - DcosApiSession.get_args_from_env assumes agents env var not set if there are no agents
> Allow running tests if there are explicitly no agents

- dcos_test_utils/marathon.py
https://jira.mesosphere.com/browse/DCOS-34466 describes that some tests leak Marathon groups (and apps, pods) during DC/OS Enterprise PR runs.
This is now interfering with other tests.
We are going to make this helper clean up pods, then we are going to apply it to DC/OS OSS and DC/OS Enterprise.
I think there is no controversy about the former.
See conversation on the JIRA about the latter - we can get to that.
- [DCOS-34466](https://jira.mesosphere.com/browse/DCOS-34466) DC/OS Enterprise Integration tests - Make sure that Marathon is cleaned up between tests.
Is this change going to be propagated up into another repo? Test the change by bumping the `dcos-test-utils` SHA to point to these changes to test …
> dcos_test_utils/marathon.py: delete marathon groups on purge

- .gitignore
- pytest_dcos/plugin.py
- tests/test_plugin.py
- tox.ini
This moves the xfailflake plugin code into dcos-test-utils so that it does not need to be duplicated for every branch and repository. It also adds a pytest hook to write out a report of all tests that are marked flakey.
- [DCOS-46439](https://jira.mesosphere.com/browse/DCOS-46439) xfailflake dashboard - collect marked issues without a cluster and without regex
> Add plugin for collecting xfailflakes

- dcos_test_utils/dcos_cli.py
Older versions of dcos-cli (e.g., `0.6.5` the default for DC/OS 1.11) do not support the `-vv` flag, only `--debug`. This PR switches dcos-test-utils to use the older flag to ensure compatibility.
- [/DCOS-46439](https://jira.mesosphere.com/browse//DCOS-46439) xfailflake dashboard - collect marked issues without a cluster and without regex
* [BACKPORT] [1.11] DCOS-46439 - Move xfailflake collection to dcos-test-utils:  https://github.com/dcos/dcos/pull/4425 / https://github.com/mesosphere/dcos-enterprise/pull/4556
> DCOS-46439 - Replace -vv with --debug in dcos-cli command line to support older versions of DC/OS CLI.

- dcos_test_utils/dcos_cli.py
This makes sure the correct DC/OS CLI URL version is used during integration
The DC/OS version is read from gen/calc.py. For DC/OS < 1.14, it will return
https://downloads.dcos.io/binaries/cli/linux/x86-64/dcos-1.XX/dcos with the
appropriate version. Starting from DC/OS 1.14 it will return the DC/OS version
agnostic CLI URL.
The URL can be overwritten through the `DCOS_CLI_URL` env var.
https://jira.mesosphere.com/browse/DCOS-45807
https://github.com/dcos/dcos/pull/4142
DC/OS versions:
- [1.10] There I think we should update the teamcity parameter as it uses an old version of dcos-test-utils in a different way.
- [1.11] https://github.com/mesosphere/dcos-enterprise/pull/4586
- [1.12] https://github.com/mesosphere/dcos-enterprise/pull/4585
- [1.13] https://github.com/dcos/dcos/pull/4211
> Use the correct CLI for the given DC/OS version

- dcos_test_utils/jobs.py
- tests/test_jobs.py
Previously, dcos-test-utils would raise an exception if jobs results were not yet ready, but exceptions are not retried, so we instead log and return False.
- [DCOS_OSS-4877](https://jira.mesosphere.com/browse/DCOS_OSS-4877) Waiting for job run to be finished, but history for that job run is not available
> DCOS_OSS-4877 - Instead of raising an exception when job results are not ready, return false so that it retries.

- dcos_test_utils/marathon.py
For such a high level tests, asserting that no tasks failed is too much implementation detail. It totally makes sense in some Marathon integration tests suite, but not here. We should just verify that the deployment finishes in some time period and how marathon makes that happen is irrelevant. We will introduce a test covering that in our suite.
Related JIRAs: DCOS-20756
> By default set ignore_failed_tasks to True

- dcos_test_utils/dcos_cli.py
This is a follow-up from
https://github.com/mesosphere/dcos-enterprise/pull/3473, we had
forgotten to remove the output assertions in dcos-test-utils too.
https://jira.mesosphere.com/browse/DCOS-51877
> Remove assertion on CLI output

- dcos_test_utils/package.py
A marathon change was introduced which does not allow the same service name to be used twice, even when that previous service was deleted. This caused integration tests to fail when running all at once. Specifically test_mom_installation would time out.
When installing a package in the UI, the service name is set to the AppId, so we don't encounter this issue. However when using the cosmos API, the service name always takes the same default value.
The fix is to randomize the AppId and set the service name to the same value.
> Randomize default app_id. Make service name = app_id by default

- dcos_test_utils/dcos_api.py
This makes one particular error slightly easier to debug.
- [DCOS_OSS-5245](DCOS_OSS-5245) Test Utils - _wait_for_srouter_slaves_endpoints - unclear failure.
I will not be urgently bumping this in DC/OS and I prefer to not do this unless a reviewer requests it.
I cannot think of a viable test for this unless we had a mock Mesos...
> Show status code when expected status code is not found

- dcos_test_utils/dcos_api.py
This continues `wait_for_dcos` in one scenario where it erroneously stopped before.
- [DCOS_OSS-5246](https://jira.mesosphere.com/browse/DCOS_OSS-5246) Test Utils - _wait_for_srouter_slaves_endpoints - 502 can be seen before 200
I have no intention of immediately bumping DC/OS. Therefore I will not do this unless a reviewer requests it.
I cannot think how to test this without a Mesos mock.
>  Continue checking Mesos slave state even after a 502

- dcos_test_utils/dcos_api.py
This enables waiting for DC/OS in more cases.
I'd really rather not do this - hopefully a reviewer can tell that this is fine. I'll do this if requested.
No tests for the same reason as above.
> Continue waiting when Mesos slave endpoint gives 503

- dcos_test_utils/dcos_cli.py
1.11 fails with dcos-test-utils master branch. Adding this small line back to fix the problem. DC/OS 1.11 CLI  cannot call "dcos plugin add", so the dcos-enterprise package must be installed.
we can see here: https://github.com/mesosphere/dcos-enterprise/blob/1.11/packages/dcos-integration-test/extra/conftest.py#L265 will call new_cli with no plugin specified
> Install dcos-enterprise CLI if not ee plugin is specified

- dcos_test_utils/dcos_api.py
This PR adds new helpers to allow tests to find the sandbox directory associated with a pod task container, and to pull the text content of files contained therein. Such helpers existed already for command (non-pod) tasks.
- [DCOS-57093](https://jira.mesosphere.com/browse/DCOS-57093) test_secret_leakage.test_pod_secret_leakage looks flaky
https://github.com/dcos/dcos/pull/6187
> Add helpers to get a pod task's sandbox and pull files from it.

- dcos_test_utils/marathon.py
What features does this change enable? What bugs does this change fix?
Always use force param for cleanup
- [DCOS-57321](https://jira.mesosphere.com/browse/DCOS-57321) DC/OS CI instability: Pod destruction fails with "App is locked by one or more deployments"
**What is the review process and when will my changes land?**
All PRs require 2 approvals using GitHub's [pull request reviews](https://help.github.com/articles/about-pull-request-reviews/).
Reviewers should be:
* Developers who understand the code being …
> Always use force when cleaning up pods

- dcos_test_utils/dcos_api.py
Remove dcos-history
- [DCOS-58529](https://jira.mesosphere.com/browse/DCOS-58529) Remove dcos-history
**What is the review process and when will my changes land?**
All PRs require 2 approvals using …
> Do not wait for dcos-histroy

- dcos_test_utils/etcd.py
Make `subprocess.run()` call compatible with python3.6 used in dc/os.
- https://jira.d2iq.com/browse/D2IQ-59030 `introduce RBAC authn&authz`
- https://jira.d2iq.com/browse/D2IQ-64356 `E2E test for custom external certificate feature`
> make subprocess.run() call args compatible with Python3.6 used in dc/os

- dcos_test_utils/dcos_api.py
The `DCOS_ACS_TOKEN` from `dcos config show core.dcos_acs_token` is an
*authentication* token and not a *login* token such as the CI token used
as the default.
> Use DCOS_ACS_TOKEN as authentication token.

- dcos_test_utils/dcos_cli.py
Enable verbose output in dcos cli to debug issues with network.
- Fixes: https://jira.d2iq.com/browse/D2IQ-69002
**What is the review process and when will my changes land?**
All PRs require 2 …
> Update DCOS CLI and enable debug

- dcos_test_utils/marathon.py
In Python integers are not guaranteed to compare for equality using identity. It just so happens that this has worked for small integers in CPython for a long time.
Changing this now, as better linting means we now get warnings about this.
[Integration …
> Change `is not 0` to `!= 0`
